#!/bin/bash

# Fill in the directory name that contains all your 42 projects that you are working on
export WORKSPACE42=$HOME/Documents
# Fill in the directory that contains all your testers
export TESTERS=$HOME/Testers

# Do not touch these gobal variables
TEMPLATE=$(dirname ${BASH_SOURCE:-$0})/template
OWN_TESTER=$TESTERS/c_testsuit

GREEN='\033[0;32m'
BLUE='\033[0;36m'
RED='\033[0;31m'
WHITE='\033[0m'
