#!/bin/bash

source $(dirname ${BASH_SOURCE:-$0})/global

for f in $(dirname ${BASH_SOURCE:-$0})/lib/*; do
  if [[ -f "$f" ]] ; then
    source $f &&
    echo -e $GREEN"sourced $f"$WHITE
  fi
done

setup-docker &&
open-docker &&
init-cbmc