#!/bin/bash
UTILS_DIR=$(dirname ${BASH_SOURCE:-$0})
source $UTILS_DIR/global

for f in $UTILS_DIR/lib/*; do
  if [[ -f "$f" ]] ; then
    source $f &&
    echo -e $GREEN"sourced $f"$WHITE
  fi
done

# setup-docker &&
# open-docker &&
# init-cbmc