#!/bin/bash

42test(){
  
}

42debug(){
  if [[ -f Makefile ]]
  then
     echo 'debug : FLAGS += -g
      debug : all'>> Makefile
  fi
}

42undebug(){
  if [[ -f Makefile ]]
  then
    sed -i "" "s/(debug : FLAGS += -g)|(debug : all)//g"
  fi
}