#!/bin/bash

42help() {
  echo -e $BLUE"
Avaliable commands:

42project <dirname>     Creates a new project directory with all corresponding testing tools and development tools.
work <project_name>     Change directory to the project's src folder
spec <project_name>     Change directory to the project's spec folder
goto-cc                 Compile project into GOTO-binaries
goto-instrument         Write assertions for found bugs to GOTO-binaries (for testsuit generation)
cbmc                    Static analyzer for .c or GOTO-binary file
init-cbmc               Initiates a docker container to run CBMC bounded model checker
"$WHITE

}