#!/bin/bash

# Creates a new project folder structure
42project() {
  if [[ ! -f $1 ]]
  then
    echo $GREEN"Creating folder $1..."$BLUE
    # Copy the template to the current directory
    cp -R $TEMPLATE/42project $1 &&
    git init $1

    # Adding Makefile and copying own testsuit to the spec directory
    if [[ -f $OWN_TESTER ]]
    then
      git clone https://gitlab.com/scaletsang/c_testsuit.git $OWN_TESTER
    fi
    ln -s $OWN_TESTER/lib $1/spec/testsuit

    # TODO: Add cbmc bound model checker tests to the spec directory

    echo $GREEN"Finished initiating a project folder."$WHITE
    echo $BLUE"Entering project folder..."$WHITE
  else
    echo $GREEN"Folder $1 exist. Opening into folder $1."$WHITE
  fi
  code $1
}
