#!/bin/bash

goto-cc() {
  local path=$(pwd | sed "s,$WORKSPACE42,,g")
  echo $GREEN"CBMC is compiling your code to into GOTO-binaries to verify your code."$WHITE
  docker exec -it cbmc $0 /data/$path/$1 ${@:2}
}

goto-instrument() {
  local path=$(pwd | sed "s,$WORKSPACE42,,g")
  echo $GREEN"CBMC is transforming any found bugs into corresponding assertions, and are adding into the GOTO-binary."$WHITE
  docker exec -it cbmc $0 /data/$path/$1 ${@:2}
}

cbmc() {
  local path=$(pwd | sed "s,$WORKSPACE42,,g")
  echo $GREEN"Running CBMC static analyser..."$WHITE
  docker exec -it cbmc $0 /data/$path/$1 ${@:2}
}

init-cbmc() {
  docker run -itd -v $WORKSPACE42:/data --name=cbmc diffblue/cbmc:5.69.1 &&
  echo $GREEN"CBMC is running in $WORKSPACE42"$WHITE
}