#!/bin/bash

open-docker() {
  if [[ -z "$(! docker stats --no-stream 2> /dev/null)" ]]; then
    printf $BLUE"starting up docker"
    open -g -a Docker
    while [[ -z "$(! docker stats --no-stream 2> /dev/null)" ]];
      do printf "."
      sleep 1
    done
    echo ""$WHITE
  else
    echo $BLUE"Docker is already running"$WHITE
  fi
}

setup-docker() {
  rm -rf ~/Library/Containers/com.docker.docker
  rm -rf ~/.docker
  rm -rf /goinfre/${USER}/docker /goinfre/${USER}/agent
  mkdir -p /goinfre/${USER}/docker /goinfre/${USER}/agent/Data
  ln -s /goinfre/${USER}/agent ~/Library/Containers/com.docker.docker
  ln -s /goinfre/${USER}/docker ~/.docker &&
  echo $BLUE"docker is already set up in goinfre"$WHITE
}